---
title: "12/1/2021 GMAC analysis and pvalue plots"
author: 
-  Jarred Kvamme, University of Idaho
date: "9/22/2021"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=8)
library(latex2exp)
library(gridExtra)
```



## variance across tissues plots




```{r, fig.cap="", echo=FALSE, message=FALSE, warning=FALSE}
#sim=read.table(file="C:/Users/Bruin/Documents/GitHub/MRPC_support/GMAC analysis/master_tables/simulations_wholeblood.txt", sep="\t", header = T)
library(ggpubr)
library(prodlim)
# sim=read.csv(file="C:/Users/Bruin/Documents/GitHub/MRPC_support/GMAC analysis/master_tables/TRIOS_imbalanced_genotypes_WB_Updated_12_10_2021.csv", header = T)

sim=read.csv(file="C:/Users/Bruin/Documents/GitHub/MRPC_support/GMAC analysis/master_tables/TRIOS_imbalanced_genotypes_WB.csv", header = T)

pc.info=read.csv(file="C:/Users/Bruin/Documents/GitHub/MRPC_support/ADDIS_ReRun/Updated_PC_Selection/Updated.PC.info.WholeBlood.csv")

new.var=cbind.data.frame(c(pc.info$updated.per.var*100,sim$Per.var.MRPC), c(pc.info$Num.pcs, sim$Num.pcs.MRPC), c(rep("Updated.PC.Selection",length(sim$Trio.Num)),rep("Old.PC.Selection",length(sim$Trio.Num))))
colnames(new.var)=c("Percent.variance", "Number.of.PCs", "Method")

new.var2=cbind.data.frame(c(pc.info$updated.per.var*100,sim$Per.var.GMAC), c(pc.info$Num.pcs, sim$Num.pcs.GMAC), c(rep("Updated.MRPC",length(sim$Trio.Num)),rep("GMAC",length(sim$Trio.Num))))
colnames(new.var2)=c("Percent.variance", "Number.of.PCs", "Method")

sim$alternative=(sim$het+2*sim$ha)/(2*rowSums(sim[,36:38]))
sim$reference=1-sim$alternative
genotypes=sim[,36:38]/rowSums(sim[,36:38])



#create color for allele frequencies of alternative or reference < 5% 
cv1=rep(0, dim(sim)[1])
cv2=replace(cv1, which(sim$alternative<=0.05 | sim$reference<=0.05), 1)
h=0.05
sim$colvar=as.factor(cv2)

A=ggplot(data = new.var2, aes(x=Number.of.PCs, y=Percent.variance, color=Method))+
  geom_point()+
  ggtitle("WholeBlood", subtitle = "GMAC vs. Updated MRPC")+
  xlab("Number of PC's")+
  ylab("%Total Variance In Expression")

B=ggplot(data = new.var, aes(x=Number.of.PCs, y=Percent.variance, color=Method))+
  geom_point()+
  ggtitle("WholeBlood", subtitle = "MRPC")+
  xlab("Number of PC's")+
  ylab("%Total Variance In Expression")

ggarrange(A, B, nrow = 2, labels = c("A", "B"))




```










## simulation(s) Median P-value plots



```{r, eval=FALSE, fig.cap="", echo=FALSE, message=FALSE, warning=FALSE,results='hide',fig.keep='all'}

#set.seed(222)


h=0.05
A=ggplot(data = sim)+
  geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(STM.median.p), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('Median Sim. Para P-value')),
       x = expression(log10('True Nominal P-value')),
       subtitle = "1000 Small True Model Simulation")+
  scale_x_continuous(limits = c(-15,0))+
  scale_y_continuous(limits = c(-15,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")



B=ggplot(data = sim)+
  geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(LTM.median.p), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('Median Sim. Para P-value')),
       x = expression(log10('True Nominal P-value')),
       subtitle = "Large True Model Simulation")+
  scale_x_continuous(limits = c(-15,0))+
  scale_y_continuous(limits = c(-15,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")

C=ggplot(data = sim)+
  geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(TGM.median.p), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('Median Sim. Para P-value')),
       x = expression(log10('True Nominal P-value')),
       subtitle = "True GMAC Model Simulation")+
  scale_x_continuous(limits = c(-15,0))+
  scale_y_continuous(limits = c(-15,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")

D=ggplot(data = sim)+
  geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(GSS.median.p), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('Median Sim. Para P-value')),
       x = expression(log10('True Nominal P-value')),
       subtitle = "GMAC Self Simulation")+
  scale_x_continuous(limits = c(-15,0))+
  scale_y_continuous(limits = c(-15,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")



ggarrange(A, B, C, D, labels = c("A","B","C","D") , nrow=2, ncol=2)

```




## simulation(s) Nominal P-value plots



```{r, fig.cap="", echo=FALSE, message=FALSE, warning=FALSE,results='hide',fig.keep='all'}

#set.seed(222)


h=0.05
A=ggplot(data = sim)+
  geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(Nominal.p.STM), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('Sim. Nominal P-value')),
       x = expression(log10('True GMAC Nominal P-value')),
       subtitle = "Small True Model Simulation")+
  scale_x_continuous(limits = c(-15,0))+
  scale_y_continuous(limits = c(-15,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")



B=ggplot(data = sim)+
  geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(Nominal.p.LTM), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('Sim. Nominal P-value')),
       x = expression(log10('True GMAC Nominal P-value')),
       subtitle = "Large True Model Simulation")+
  scale_x_continuous(limits = c(-15,0))+
  scale_y_continuous(limits = c(-15,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")


C=ggplot(data = sim)+
  geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(Nominal.p.TGM), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('Sim. Nominal P-value')),
       x = expression(log10('True GMAC Nominal P-value')),
       subtitle = "True GMAC Model Simulation")+
  scale_x_continuous(limits = c(-15,0))+
  scale_y_continuous(limits = c(-15,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")

D=ggplot(data = sim)+
  geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(Nominal.p.GSS), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('Sim. Nominal P-value')),
       x = expression(log10('True GMAC Nominal P-value')),
       subtitle = "GMAC Self Simulation")+
  scale_x_continuous(limits = c(-15,0))+
  scale_y_continuous(limits = c(-15,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")



ggarrange(A, B, C, D, labels = c("A","B","C","D") , nrow=2, ncol=2)

```



```{r, fig.cap="", echo=FALSE, message=FALSE, warning=FALSE,results='hide',fig.keep='all'}

A=ggplot(data = sim)+
  geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(Med.pvalue.GMAC), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('True Para. P-value')),
       x = expression(log10('True Nominal P-value')),
       subtitle = "Nominal Vs. Parametric")+
  scale_x_continuous(limits = c(-15,0))+
  scale_y_continuous(limits = c(-15,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")

sim$perm.p.GMAC.pseudo=sim$Perm.p.GMAC
sim$med.p.GMAC.pseudo=sim$Med.pvalue.GMAC
sim$med.p.GMAC.pseudo=replace(sim$med.p.GMAC.pseudo, which(sim$Med.pvalue.GMAC<=2e-16), 1e-5)
sim$perm.p.GMAC.pseudo=replace(sim$perm.p.GMAC.pseudo, which(sim$Perm.p.GMAC==0), 1)


B=ggplot(data = sim)+
  geom_point(aes(x=log10(med.p.GMAC.pseudo), y=log10(perm.p.GMAC.pseudo), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('True Perm. P-value')),
       x = expression(log10('True Para. P-value')),
       subtitle = "Parametric vs Permutation")+
  scale_x_continuous(limits = c(-5,0))+
  scale_y_continuous(limits = c(-5,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")


C=ggplot(data = sim)+
  geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(perm.p.GMAC.pseudo), color=colvar))+
  theme(legend.position = "none")+
  labs(y = expression(log10('True Perm. P-value ')),
       x = expression(log10('True Nominal P-value ')),
       subtitle = "Nominal vs Permutation")+
  #scale_x_continuous(limits = c(0,0.003))+
  #scale_y_continuous(limits = c(-15,0))+
  geom_abline(intercept = 0, slope = 1, linetype="dotted")+
  geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
  geom_hline(yintercept = log10(h), color="red", linetype="dashed")


# D=ggplot(data = sim)+
#   geom_point(aes(x=log10(GMAC.Nominal.p), y=log10(perm.p.GMAC.pseudo), color=colvar))+
#   theme(legend.position = "none")+
#   labs(y = expression(log10('True Perm. P-value ')),
#        x = expression(log10('True Nominal P-value ')),
#        subtitle = "Nominal vs Permutation")+
#   #scale_x_continuous(limits = c(0,0.003))+
#   #scale_y_continuous(limits = c(0,0.003))+
#   geom_abline(intercept = 0, slope = 1, linetype="dotted")+
#   geom_vline(xintercept = log10(h), color="red", linetype="dashed")+
#   geom_hline(yintercept = log10(h), color="red", linetype="dashed")

ggarrange(A, B, C, D, labels = c("A","B","C","D") , nrow=2, ncol=2)

```



























